### ISSUE TITLE
UI Improvement: Add cross button(replacing delete button) and minimize few card details. 

### ISSUE THREAD

**Issue by Git-Harshit** [yashchaudhari008/Codechef_Cards#2]
Having profiles saved in a local memory is alright since it prevents typing the same handles, again and again, every time open this tool, but I guess they do not get cleared from storage even when the delete button is clicked, due to which they get temporarily removed from the page, but get reappeared sometimes as the page is reloaded or visited again. This issue has been observed with multiple additions and deletions. I believe this is an issue and needs to be fixed. 

Also, for the current temporary removal functionality of the Delete button, a cross button at the top-right could be considered that could either remove the card HTML straightaway or could also just set its visibility to hidden or display to none. Along with it, can we also have a card minimize button alongside? Any other suggestions are also welcome.

**Comment by yashchaudhari008** [comment]
> > * Deleted profiles do not appear on refresh!, I can't reproduce the bug
> 
> Regarding this,
> 
> When you're grabbing the username from the card's `.username` component in `deleteUser` function, because of the format from the API and how you append the text to the HTML, you're actually getting the username in the format `(username:actualUsername)`. So, when you try to use the `Set.prototype.delete` method on the `users` set, you're not actually deleting anything. In the end, you're only removing the card HTML and not from the local storate.
> 
> To reproduce the bug you just have to have added a bunch of users, delete some of them, and see that the array of users in the local storage has not changed.

I think API only breaks when user do not have any stars shown in there username. Right?

**Comment by AnsellMaximilian** [comment]
> I think API only breaks when user do not have any stars shown in there username. Right?
> Also let's make separate issue for the same!

Yes, you are right! The API gives the incorrect format only when the user does not have any stars, but you are still adding brackets into the HTML, so deleting from the Set still wouldn't work.
