### ISSUE TITLE
UserName Input borders problem

### ISSUE THREAD

**Issue by omrsfylmz** [yashchaudhari008/Codechef_Cards#22]
![Screen Shot 2021-10-12 at 19 51 30](https://user-images.githubusercontent.com/40966566/136997545-34334700-4034-4465-8d0f-6a2c64c49388.png)

When I selected this input, Input borders not look like good I can fix this style problem

**Comment by yashchaudhari008** [comment]
@omrsfylmz Okay, just make changes fixing border and make sure your changes go with UI
Also don't make other changes other than border issue, Thanks
