### ISSUE TITLE
UI Improvement : Changing card colour according to codechef star colour.

### ISSUE THREAD

**Issue by jaiakash** [yashchaudhari008/Codechef_Cards#25]
By default it shows the card in purple colour. It would be much better to change the colour according to the rating of the user accordingly.
![image](https://user-images.githubusercontent.com/33419526/137116167-bf3265ac-6179-4853-ab70-39cc416a9c0a.png)

Co-incidently, i am 4 star on codechef, and it was showing purple. But my friend who is 5 star, her profile was also showing purple. She suggested for yellow colour for her profile. From there I got this idea :+1: 
Please add any more improvements, I would like to contribute to the this issue.

**Comment by jaiakash** [comment]
For rating card, i completed the colour change feature according to star of user.
But what should i do for the colour for card header?

- [ ] Have both card header and rating of same colour. Like this ![image](https://user-images.githubusercontent.com/33419526/137601314-76828251-6f5f-466f-b0b8-4e6c145bac90.png)
- [ ] Have card header a bit pale and rating of a bit dark colour. As was for purple colour 
![image](https://user-images.githubusercontent.com/33419526/137601386-59f6faec-14c7-4f84-843d-57ba8365a65c.png)
- [ ] Have the card header colour as white (or some other colour) and rating card as star colour. Like this 
![image](https://user-images.githubusercontent.com/33419526/137601522-daf1fcdd-2b88-4daf-991f-22a2a451e8d1.png)

What do you think?

**Comment by yashchaudhari008** [comment]
> For rating card, i completed the colour change feature according to star of user.
> But what should i do for the colour for card header?
> 
> - [ ] Have both card header and rating of same colour. Like this ![image](https://user-images.githubusercontent.com/33419526/137601314-76828251-6f5f-466f-b0b8-4e6c145bac90.png)
> - [ ] Have card header a bit pale and rating of a bit dark colour. As was for purple colour 
> ![image](https://user-images.githubusercontent.com/33419526/137601386-59f6faec-14c7-4f84-843d-57ba8365a65c.png)
> - [ ] Have the card header colour as white (or some other colour) and rating card as star colour. Like this 
> ![image](https://user-images.githubusercontent.com/33419526/137601522-daf1fcdd-2b88-4daf-991f-22a2a451e8d1.png)
> 
> What do you think?

First (white text on header) or second (will look better)
Try second approach, if it looks good. We can proceed
