### ISSUE TITLE
Feature Request: Arrange cards according to rating.

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/Codechef_Cards#3]
- Currently cards are displayed in the order they were added(username).
<br />
Let cards be arranged according to the rating of user. (Probably Ascending Order)

**Comment by the-lightstack** [comment]
Can I try to solve this issue?

**Comment by the-lightstack** [comment]
I am looping over all the RootNode's Child Elements and checking, if the card to be inserted has a higher or lower rating. If the current Card is lower and the previous is higher, I insert it at that point. Then I check for exceptions like the first element being higher, the last lower or equal values. You are right about the unordered style of `Set`s, but [they always have the same iteration order](https://stackoverflow.com/questions/33089695/how-can-i-sort-an-es6-set)

**Comment by yashchaudhari008** [comment]
Okay but here I don't think sorting Set is necessary,
Still try to implement the changes which are in your mind.
Keep me updated👍🏼✌️
> Try to make few changes as possible and make it simple.
