### ISSUE TITLE
UI Improvement: Auto focus input when users open the menu-bar

### ISSUE THREAD

**Issue by AnsellMaximilian** [yashchaudhari008/Codechef_Cards#34]
After opening the menu bar, the user has to click on the input field before they can add usernames, creating a little inconvenience, especially since the menu bar closes after a username is added. So when a user wants to add a bunch of usernames in succession, they have to keep clicking on the chevron icon and the input element.

Whenever the user toggles the menu-bar to reveal the input for the username, the input element should receive focus immediately so the user can type immediately without having to click the input element.

**Comment by yashchaudhari008** [comment]
Focusing on input element might be helpful 👍
