### ISSUE TITLE
UI/UX : Redesign Topbar

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/Codechef_Cards#59]
The current Topbar doesn't look well and feels odd. (Especially for larger screens)

![image](https://user-images.githubusercontent.com/29065088/189533665-b7c8aa85-a5c3-41aa-98d4-28a2cf7e7862.png)

**Comment by Manish5121** [comment]
can i try to work on this ?

**Comment by yashchaudhari008** [comment]
Sure, just add a screenshot before making any PR.
