### ISSUE TITLE
align item center on button

### ISSUE THREAD

**Issue by nileshlad09** [yashchaudhari008/Codechef_Cards#60]
![image](https://user-images.githubusercontent.com/89249015/193413333-37e33e30-7151-4c87-9284-0f80b5245da8.png)

here i can align them center so they look better

**Comment by yashchaudhari008** [comment]
I am not seeing it on Chrome Browser. Which device and browser are you using?

**Comment by nileshlad09** [comment]
in chrome browser

**Comment by yashchaudhari008** [comment]
I am unable to reproduce the issue! Please check your system once and also try it on multiple browsers. Attach full page screenshots if possible.

**Comment by nileshlad09** [comment]
![image](https://user-images.githubusercontent.com/89249015/193414342-4e5f4eab-41c3-4d6a-87d7-f338c01a516d.png)

**Comment by yashchaudhari008** [comment]
I tested it on firefox, chrome. It's working fine, your chrome settings maybe affecting this issue.
