### ISSUE TITLE
Alert user when Invalid/already_existing username is entered.

### ISSUE THREAD

**Issue by govind2404** [yashchaudhari008/Codechef_Cards#7]
Currently invalid username is printing in console ( console.alert("Cannot Fetch Data From API, ",error) ) we can show the message as alert or we can print the message on screen, so that user can know that the username is invalid.

**Comment by govind2404** [comment]
@yashchaudhari008 I didn't understand this "Also when username is already present in list". What do you mean by this?

**Comment by yashchaudhari008** [comment]
When user tries to create duplicate entry he should be notified that it's already present in cards.
Example:- usernames = [A,B,C]
and user tries to add B again. He Should be notified.
